# Generated by Django 5.2.17 on 2026-09-21 10:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateField(verbose_name="Дата начала")),
                (
                    "seats_total",
                    models.PositiveSmallIntegerField(
                        default=8, verbose_name="Всего мест"
                    ),
                ),
                (
                    "seats_available",
                    models.PositiveSmallIntegerField(
                        default=8, verbose_name="Доступно мест"
                    ),
                ),
                (
                    "instant_booking",
                    models.BooleanField(default=False, verbose_name="Мгновенная бронь"),
                ),
            ],
            options={
                "verbose_name": "Выезд",
                "verbose_name_plural": "Даты выездов",
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "region",
                    models.CharField(blank=True, max_length=120, verbose_name="Регион"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "best_season",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Лучший сезон"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="destinations/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Показывать на главной"
                    ),
                ),
            ],
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Название")),
                (
                    "city",
                    models.CharField(
                        default="Бишкек", max_length=100, verbose_name="Город"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="О команде")),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Проверен"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        max_digits=2,
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "response_rate",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Ответы вовремя, %"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="Телефон"),
                ),
            ],
            options={
                "verbose_name": "Организатор",
                "verbose_name_plural": "Организаторы",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=160, verbose_name="Имя гостя"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=40, verbose_name="Телефон")),
                (
                    "guests",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Гостей"),
                ),
                (
                    "total_price",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Сумма, сом"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("confirmed", "Подтверждена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="new",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "departure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="marketplace.departure",
                        verbose_name="Выезд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("summary", models.TextField(verbose_name="Краткое описание")),
                (
                    "duration_days",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Дней"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Лёгкий"),
                            ("medium", "Средний"),
                            ("hard", "Сложный"),
                        ],
                        default="easy",
                        max_length=12,
                        verbose_name="Сложность",
                    ),
                ),
                (
                    "group_size",
                    models.PositiveSmallIntegerField(
                        default=8, verbose_name="Размер группы"
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Цена, сом")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "reviews_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество отзывов"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="tours/", verbose_name="Главное фото"
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, verbose_name="Показывать на главной"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tours",
                        to="marketplace.destination",
                        verbose_name="Направление",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tours",
                        to="marketplace.operator",
                        verbose_name="Организатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тур",
                "verbose_name_plural": "Туры",
                "ordering": ["-featured", "title"],
            },
        ),
        migrations.AddField(
            model_name="departure",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departures",
                to="marketplace.tour",
                verbose_name="Тур",
            ),
        ),
        migrations.AddConstraint(
            model_name="departure",
            constraint=models.UniqueConstraint(
                fields=("tour", "starts_at"), name="unique_tour_departure"
            ),
        ),
    ]
