# Generated by Django 5.2.17 on 2026-09-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GallerySlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Название")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Подпись"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="gallery/", verbose_name="Изображение"
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        help_text="Например /images/hero-song-kol.png. Используется, если файл не загружен.",
                        max_length=240,
                        verbose_name="Путь к изображению",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Показывать"),
                ),
            ],
            options={
                "verbose_name": "Слайд карусели",
                "verbose_name_plural": "Слайды карусели",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_eyebrow",
                    models.CharField(
                        default="Путешествия по Кыргызстану",
                        max_length=120,
                        verbose_name="Надпись над заголовком",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Страна, которую стоит прожить.",
                        max_length=180,
                        verbose_name="Главный заголовок",
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="Маршруты от тех, кто знает каждую дорогу.",
                        max_length=220,
                        verbose_name="Подзаголовок",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True, upload_to="site/", verbose_name="Фоновое фото"
                    ),
                ),
                (
                    "intro_label",
                    models.CharField(
                        default="01 / О нас",
                        max_length=80,
                        verbose_name="Метка блока о нас",
                    ),
                ),
                (
                    "intro_title",
                    models.CharField(
                        default="Мы собираем настоящий Кыргызстан в одном месте.",
                        max_length=220,
                        verbose_name="Заголовок блока о нас",
                    ),
                ),
                (
                    "intro_text",
                    models.TextField(
                        default="Не каталог безликих экскурсий, а путешествия с характером: небольшие группы, местные проводники и понятное бронирование без переписок в мессенджерах.",
                        verbose_name="Текст блока о нас",
                    ),
                ),
                (
                    "gallery_label",
                    models.CharField(
                        default="Моменты путешествия",
                        max_length=100,
                        verbose_name="Метка галереи",
                    ),
                ),
                (
                    "gallery_title",
                    models.CharField(
                        default="Кыргызстан в кадре",
                        max_length=180,
                        verbose_name="Заголовок галереи",
                    ),
                ),
                (
                    "trips_label",
                    models.CharField(
                        default="02 / Ближайшие поездки",
                        max_length=100,
                        verbose_name="Метка туров",
                    ),
                ),
                (
                    "trips_title",
                    models.CharField(
                        default="Выберите свой темп",
                        max_length=180,
                        verbose_name="Заголовок туров",
                    ),
                ),
                (
                    "promise_label",
                    models.CharField(
                        default="03 / Почему мы",
                        max_length=100,
                        verbose_name="Метка преимуществ",
                    ),
                ),
                (
                    "promise_title",
                    models.CharField(
                        default="Всё важное известно до начала пути.",
                        max_length=220,
                        verbose_name="Заголовок преимуществ",
                    ),
                ),
                (
                    "places_label",
                    models.CharField(
                        default="04 / Куда поехать",
                        max_length=100,
                        verbose_name="Метка направлений",
                    ),
                ),
                (
                    "places_title",
                    models.CharField(
                        default="Четыре стороны страны",
                        max_length=180,
                        verbose_name="Заголовок направлений",
                    ),
                ),
                (
                    "partner_title",
                    models.CharField(
                        default="Вы создаёте маршрут. Мы приводим гостей.",
                        max_length=220,
                        verbose_name="Заголовок для партнёров",
                    ),
                ),
                (
                    "partner_text",
                    models.CharField(
                        default="Управляйте датами, местами и заявками в одном кабинете.",
                        max_length=220,
                        verbose_name="Текст для партнёров",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Главная страница",
                "verbose_name_plural": "Главная страница",
            },
        ),
    ]
